# Generated by Django 5.1 on 2025-03-12 01:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DataSourceRanking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dataSource",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("apple_health", "Apple Health"),
                            ("fitbit", "Fitbit"),
                            ("health_connect", "Health Connect"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("rank", models.IntegerField()),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Record",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("startDate", models.DateTimeField()),
                ("endDate", models.DateTimeField()),
                ("creationDate", models.DateTimeField()),
                (
                    "sourceVersion",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("sourceName", models.CharField(max_length=200)),
                ("source", models.CharField(max_length=200)),
                ("value", models.CharField(max_length=200)),
                ("unit", models.CharField(blank=True, max_length=200, null=True)),
                ("type", models.CharField(max_length=200)),
                ("device", models.CharField(blank=True, max_length=200, null=True)),
                ("admin_create_date", models.DateTimeField()),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Workout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("startDate", models.DateTimeField()),
                ("endDate", models.DateTimeField()),
                ("creationDate", models.DateTimeField()),
                (
                    "sourceVersion",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("sourceName", models.CharField(max_length=200)),
                ("source", models.CharField(max_length=200)),
                ("device", models.CharField(blank=True, max_length=200, null=True)),
                ("durationUnit", models.CharField(max_length=200)),
                ("duration", models.IntegerField()),
                ("workoutActivityType", models.CharField(max_length=200)),
                ("admin_create_date", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkoutMetadataEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=200)),
                ("key", models.CharField(max_length=200)),
                (
                    "workout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="healthdatamodel.workout",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "WorkoutMetadataEntry",
            },
        ),
    ]
