# Generated by Django 5.2.11 on 2026-03-02 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("healthdatamodel", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WearableConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_source",
                    models.CharField(
                        choices=[
                            ("apple_health", "Apple Health"),
                            ("fitbit", "Fitbit"),
                            ("health_connect", "Health Connect"),
                        ],
                        help_text="The data pipeline this connection feeds (apple_health, fitbit, health_connect).",
                        max_length=100,
                    ),
                ),
                (
                    "device_brand",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("apple", "Apple"),
                            ("samsung", "Samsung"),
                            ("fitbit", "Fitbit"),
                            ("garmin", "Garmin"),
                            ("oura", "Oura"),
                            ("whoop", "WHOOP"),
                            ("datajet", "DataJet"),
                        ],
                        default="",
                        help_text="Brand of the physical device (apple, fitbit, garmin …).",
                        max_length=100,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("disconnected", "Disconnected"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "preferred_for_sleep",
                    models.BooleanField(
                        default=False,
                        help_text="If True, this connection's device_brand is preferred when choosing sleep data.",
                    ),
                ),
                ("connected_at", models.DateTimeField(auto_now_add=True)),
                ("disconnected_at", models.DateTimeField(blank=True, null=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wearable_connections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["connected_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("customer", "data_source"),
                        name="unique_customer_data_source",
                    )
                ],
            },
        ),
    ]
