# Generated by Django 6.0.6 on 2026-07-07 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthdatamodel', '0004_record_google_health_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasourceranking',
            name='dataSource',
            field=models.CharField(blank=True, choices=[('apple_health', 'Apple Health'), ('fitbit', 'Fitbit'), ('garmin', 'Garmin'), ('google_health', 'Google Health'), ('health_connect', 'Health Connect')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='wearableconnection',
            name='data_source',
            field=models.CharField(choices=[('apple_health', 'Apple Health'), ('fitbit', 'Fitbit'), ('garmin', 'Garmin'), ('google_health', 'Google Health'), ('health_connect', 'Health Connect')], help_text='The data pipeline this connection feeds (apple_health, fitbit, health_connect).', max_length=100),
        ),
    ]
