# Generated by Django 6.0.7 on 2026-08-05 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthdatamodel', '0008_record_strava_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='wearableconnection',
            name='activated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
