# Generated by Django 6.0.6 on 2026-08-03 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("healthdatamodel", "0008_record_strava_choice"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("apple_health", "Apple Health"),
                            ("fitbit", "Fitbit"),
                            ("garmin", "Garmin"),
                            ("google_health", "Google Health"),
                            ("health_connect", "Health Connect"),
                            ("oura", "Oura"),
                            ("strava", "Strava"),
                            ("whoop", "WHOOP"),
                        ],
                        max_length=100,
                    ),
                ),
                ("device", models.CharField(default="", max_length=200)),
                (
                    "metric",
                    models.CharField(
                        choices=[
                            ("active_kcal", "Active energy (kcal)"),
                            ("basal_kcal", "Basal energy (kcal)"),
                            ("steps", "Steps"),
                        ],
                        max_length=20,
                    ),
                ),
                ("day", models.DateField()),
                ("resolution_minutes", models.PositiveSmallIntegerField()),
                ("values", models.JSONField()),
                ("admin_create_date", models.DateTimeField()),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["customer", "metric", "day"],
                        name="activityday_cust_metric_day_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "customer",
                            "source",
                            "device",
                            "metric",
                            "day",
                            "resolution_minutes",
                        ),
                        name="unique_activityday_key",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SleepDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("apple_health", "Apple Health"),
                            ("fitbit", "Fitbit"),
                            ("garmin", "Garmin"),
                            ("google_health", "Google Health"),
                            ("health_connect", "Health Connect"),
                            ("oura", "Oura"),
                            ("strava", "Strava"),
                            ("whoop", "WHOOP"),
                        ],
                        max_length=100,
                    ),
                ),
                ("device", models.CharField(max_length=200)),
                ("day", models.DateField()),
                ("intervals", models.JSONField(default=list)),
                ("admin_create_date", models.DateTimeField()),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["customer", "day"], name="sleepday_customer_day_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("customer", "device", "day"),
                        name="unique_sleepday_customer_device_day",
                    )
                ],
            },
        ),
    ]
